---
antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Red Hat Ansible Automation Platform and HashiCorp Terraform Enterprise"
      solveButton: true
    - name: module-02
      label: "Trigger Infrastructure Provisioning and automation from Terraform Enterprise - Part 1"
    - name: module-03
      label: "Trigger Infrastructure Provisioning and automation from Terraform Enterprise - Part 2"
    - name: module-04
      label: "How to create a HashiCorp-enabled Execution Environment"

tabs:
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
    external: false
  - name: Terraform Enterprise (TFE)
    url: https://tfe-https-${guid}.${domain}/session
    external: true
  - name: HashiCorp Vault
    url: https://vault-${guid}.${domain}/ui/vault/unseal
    external: true
  - name: VS Code
    url: https://vscode-${guid}.${domain}
    external: false
  - name: "Terminal"
    url: /wetty_vscode
  - name: Cloud (AWS)
    url: /cloud
  - name: AAP-External
    url: https://control-${guid}.${domain}/
    external: true
